# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipleaseP10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire'
  # Pods for RecipleaseP10

  target 'RecipleaseP10Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecipleaseP10UITests' do
    # Pods for testing
  end

end
